export const REQUEST_TIMEOUT_MIN_SECONDS = 1;
export const REQUEST_TIMEOUT_MAX_SECONDS = 120;

export const MILLISECONDS_IN_SECOND = 1000;
export const SECONDS_IN_MINUTE = 60;
export const TIME_DISPLAY_PAD_LENGTH = 2;
export const JSON_PRETTY_PRINT_SPACES = 2;

export const PIPELINE_MIN_SENDING_DURATION_MS = 400;
export const MOCK_REQUEST_DELAY_MS = 2000;
export const MOCK_REQUEST_TIMEOUT_BUFFER_MS = 15;

export const HTTP_STATUS_OK = 200;
export const HTTP_STATUS_BAD_REQUEST = 400;
export const HTTP_STATUS_REQUEST_TIMEOUT = 408;
export const HTTP_STATUS_CLIENT_CLOSED_REQUEST = 499;
